[package]
name = "shaoziclaw-app"
version = "5.5.27"
description = "勺子Claw - 餐饮人的超级AI大脑"
authors = ["ShaoziClaw Team"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["devtools"] }
tauri-plugin-updater = "2"
tauri-plugin-shell = "2"
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-http = "2"
dirs = "5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
reqwest = { version = "0.12", features = ["json", "rustls-tls", "blocking"], default-features = false }
rusqlite = { version = "0.31", features = ["bundled"] }
chrono = { version = "0.4", features = ["serde"] }
url = "2.5.8"
base64 = "0.22"
lazy_static = "1.4"
lancedb = "0.27"
arrow-array = "57"
arrow-schema = "57"
log = "0.4"
tauri-plugin-log = "2"
sha2 = "0.10"
sha1 = "0.10"
hmac = "0.12"
uuid = { version = "1", features = ["v4"] }
urlencoding = "2"

[profile.dev]
incremental = true

[profile.release]
codegen-units = 16
lto = false
opt-level = "s"
strip = true
